version: '3.8'
services:
  redis:
    image: redis
    container_name: redis
  oauthserver:
    build: .
    container_name: oauthserver
    ports:
      - "8080:8080"
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    volumes:
      - /home/ubuntu/DsCeltic_IoT_OAuthServer/logs:/app/logs
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: bZGPt9zQZ7aAtv+T]6}(*EfDONfO.R
      MYSQL_DATABASE: dsiot
      MYSQL_USER: dsiotAppServer
      MYSQL_PASSWORD: bZGPt9zQZ7aAtv+T]6}(*EfDONfO.R
    ports:
      - "3306:3306"
    volumes:
      - /etc/mysql/conf.d/init.sql:/docker-entrypoint-initdb.d/init.sql
#      - /home/ubuntu/DsCeltic_IoT_OAuthServer/init.sql:/docker-entrypoint-initdb.d/init.sql
