version: '3.8'
services:
  redis:
    image: redis
    container_name: redis
  oauthserver:
    build: .
    container_name: oauthserver
    ports:
      - "8080:8080"
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

