# Spring MVC
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  datasource:
     url: jdbc:mysql://3.37.23.88:3306/ds_iot?characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
#     url: jdbc:mysql://3.37.23.88:3306/ds_iot_test_0415?characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    #  url: jdbc:mysql://127.0.0.1:3306/dsiot?characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&verifyServerCertificate=false&useSSL=false
     username: dsiotAppServer
#     username: root
     password: bZGPt9zQZ7aAtv+T]6}(*EfDONfO.R
#     password: root@1234
     driver-class-name: com.mysql.cj.jdbc.Driver
     hikari:
      maximum-pool-size: 200
      connection-timeout: 11000
      max-lifetime: 1800000 # 30분
      idle-timeout: 300000 # 5분
      minimum-idle: 5
      connection-test-query: SELECT 1

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1093285216231-8c6odcqlbklnn05a31q7lvbqu2gcq14r.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

# Mybatis
mybatis:
  config-location: classpath:mybatis-config.xml

# Redis
redis:
  host: localhost
  port: 6379

# TIME OUT
server:
  port: 8080
  timeout: 5

# \uAE30\uAE30 Model Code (\uAD6C\uD615, \uC2E0\uD615)
device:
  model:
    code: "{oldModel: ' ESCeco13S', 
    newModel: ' DCR-91/WF', 
    ventilation: ' DCR-47/WF', 
    heatpump160: '   DHR-160',
    heatpump166: '   DHR-166',
    heatpump260: '   DHR-260',
    heatpump260A: ' DHR-260A'
    }"

# Server Token
app:
  token:
    path_app_public_key: apikeys/app-public-key
    path_app_private_key: apikeys/app-private-key
  server: # Server Address
    address:
      short:
#        gw: 127.0.0.1:7579
          gw: 172.31.50.223:7579
        #  gw: 172.31.57.74:7579
      long:
#        gw: http://127.0.0.1:10010/AppToGwServer
         gw: http://172.31.50.223:10010/AppToGwServer
#         gw: http://172.31.57.74:10010/AppToGwServer
#      push: http://127.0.0.1:8082/AppServerToPushServer
      push: http://172.31.50.223:8082/AppServerToPushServer
#      push: http://172.31.57.74:8082/AppServerToPushServer
#
# Logging
logging:
  level:
      root: INFO  # 기본 로그 레벨을 INFO로 설정
      org.springframework: WARN  # Spring 관련 로그를 WARN으로 설정
      org.hibernate: ERROR  # Hibernate 관련 로그를 ERROR로 설정
      com.zaxxer.hikari: ERROR  # Hikari 관련 로그를 ERROR로 설정
      org.apache.ibatis: ERROR  # MyBatis 관련 로그를 ERROR로 설정
      org.mybatis: DEBUG
#    com.zaxxer.hikari.HikariConfig: INFO
#    com.zaxxer.hikari: TRACE
  file:
     path: /home/ubuntu/DsCeltic_IoT_OAuthServer/logs
     name: oauthserver.log

influx:
  url: http://172.31.50.223:8086
#  url: http://3.37.23.88:8086
  token: K9sA9ByCrOwD4kmawbaCtYsfa-OSExboS3ptTTFaMWCXVGpsENn7AumLinC8lEUaazd8rNs-nj-X909Rawa_NQ==
  org:  DaesungCelticEnersys
  bucket: ds_iot_command_temp